### ISSUE TITLE
在useEffect中，或者useReady等函数中。setFieldsValue、setFieldValue会失效。

### ISSUE THREAD

**Issue by onlyc0302** [P4X666/taro-form#1]
通过按钮点击触发 setFieldsValue ,是生效的。
但是在页面进来，想要通过此fun赋值，不起作用。
`
 useEffect(() => {

    if (formRef) {
      console.log('formRef: ', formRef);
      formRef.current.setFieldsValue({
        username: 'hello1'
      });
    }

  }, [formRef]);
`

// 此处依赖加不加formRef,都不行。

查看源码，在useFormStore.ts文件中。
setFieldsValue 函数中。
79行的fields第一次打印为{}，const [fields, dispatch] = useReducer(fieldsReducer, {});
后续才会打印出fields
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/24369193/211286600-c5a89bc9-2a6e-4cde-b6ea-67668526fae2.png">

导致此处dispatch 不会触发。
`
const setFieldsValue = (userFields: Record<string, any>) => {

    if (!isObject(userFields)) return;
    Object.keys(userFields).forEach(name => {
      if (fields.hasOwnProperty(name)) {
        dispatch({
          type: "updateValue",
          name,
          value: userFields[name]
        });
      }
    });
  };
`

**Comment by P4X666** [comment]
虽然不知道你的使用场景，但是我猜测你是想初始化表单数据，方法有以下两种：
1.  使用 initialValues 来初始化数据
2.  你在源代码中也看到了，fields是用的useReducer来更新的，所以你需要异步包裹一下即可
![image](https://user-images.githubusercontent.com/50615274/211344718-f4f388f3-e6f8-4e77-8b1d-c9955f0b7cf7.png)

**Comment by onlyc0302** [comment]
> 1. 使用

感谢您在百忙之中回复我。  
您的这个添加promise包裹是有效的

这里的使用场景是。
编辑表单时，表单值回显。 之前使用antd的表格也是习惯用setFieldsValue 来设置初始值。

在这里我尝试用
```
const [data, setData] = useSteta(null)
useEffect(() => {
     setData({username: 'hello'})
}, [])
<Form initialValues ={data}></Form>
```
这个data是异步获取，在useState中 setDate()没有起作用。

所以提了issus。

那么这里是否还有改造的可能，使得在生命周期中使用 setFieldsValue 不用包裹promise呢。
当然目前已经足够使用了，还需要学习一下您的源码、实现思路。

**Comment by P4X666** [comment]
首先，感谢你的建议；
其次，根据你提供的代码以及描述的条件来看，setFieldsValue是没问题的，因为你说data是异步获取的，而 setFieldsValue 的底层是调用的useReducer，优先级是明显高于异步的，所以理论上来说，在异步场景下setFieldsValue是没问题的；
最后，我会尽快更新一版来修复同步场景下setFieldsValue不生效的问题
